import type { MealCategory } from '~/types';

export const brunch: MealCategory = {
  title: 'Brunch Menüs',
  meals: [
    {
      name: 'Sonnengruß',
      ingredients: [
        'Parmaschinken',
        'Italienische Salami',
        'Tomaten',
        'Mozzarella',
        { name: 'Oliven', dietaryLabels: [2] },
        'Parmesan',
        'Burrata',
        'Cherry-Tomaten in Olivenöl',
        'Frischkäse',
        'Honigmelone',
        'Marmelade',
        'Brotkorb',
      ],
    },
    {
      name: 'Griechisches Frühstück',
      ingredients: [
        'Feta',
        'Tomaten',
        { name: 'Oliven', dietaryLabels: [2] },
        'rote Zwiebeln',
        'Griechischer Joghurt mit Honig',
        'Gurke',
        'gekochtes Ei',
        'Marmelade',
        'Baguette',
      ],
    },
    {
      name: 'Pariser Frühstück',
      ingredients: [
        { name: 'Cappucino', dietaryLabels: [7] },
        'Buttercroissant',
        'Butter',
        'Rührei',
        'Marmelade',
        'Camembert',
        'Parmaschinken',
        'Weintrauben',
        'Baguette',
      ],
    },
    {
      name: 'Penzinger Frühstück',
      ingredients: [
        'Glas Orangensaft',
        'Wurst & Bergkäse',
        'Rührei',
        'Knuspriger Bacon',
        'Tomate',
        'Gurke',
        'Butter',
        'Marmelade',
        'Glas Joghurt mit Früchten',
        'Brotkorb',
      ],
    },
    {
      name: 'Seeblick',
      ingredients: [
        'Glas Orangensaft',
        'Croissant',
        'Butter',
        'Marmelade',
        'Pink Hummus Aufstrich',
        'Frischkäse',
        'Camembert',
        'Bergkäse',
        'Tomate',
        'Gurke',
        'Ei im Glas',
        'Brotkorb',
      ],
    },
    {
      name: 'Morgentau',
      ingredients: [
        'Räucherlachs',
        'Meerrettich-Frischkäse',
        'Zwiebeln',
        'Ei im Glas',
        'Bergkäse',
        'Avocado',
        'Butter',
        'Marmelade',
        'Joghurt mit Früchten',
        'Green 18 Hausbrot',
      ],
    },
    {
      name: 'Bayrisches Frühstück',
      ingredients: ['1 Paar Münchner Weißwürste', 'Süßer Senf', 'Breze'],
    },
  ],
};
